CREATE TEMPORARY EXTERNAL TABLE IF NOT EXISTS hw2_test(
id int,
if1 Float,
if2 Float,
if3 Float,
if4 Float,
if5 Float,
if6 Float,
if7 Float,
if8 Float,
if9 Float,
if10 Float,
if11 Float,
if12 Float,
if13 Float,
cf1 string,
cf2 string,
cf3 string,
cf4 string,
cf5 string,
cf6 string,
cf7 string,
cf8 string,
cf9 string,
cf10 string,
cf11 string,
cf12 string,
cf13 string,
cf14 string,
cf15 string,
cf16 string,
cf17 string,
cf18 string,
cf19 string,
cf20 string,
cf21 string,
cf22 string,
cf23 string,
cf24 string,
cf25 string,
cf26 string,
day_number string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' WITH SERDEPROPERTIES('separatorChar'='\t')
STORED AS TEXTFILE
LOCATION '/datasets/criteo/criteo_test_large_features';
--LOCATION '/user/zakharovart01/test_dir';
--LOAD DATA INPATH '/user/zakharovart01/test_data' INTO TABLE hw2_test;
